name: wecare
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  animated_text_kit: ^2.2.0
  url_launcher: 5.4.11
  shared_preferences: 0.5.7+3
  http: 0.12.1
  dynamic_theme: 1.0.1
  pie_chart: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/